# Configuration for the metrics-generator
tempo:
  metricsGenerator:
    enabled: true
    remoteWriteUrl: " http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write"    

tempoQuery:
  enabled: true
Service:
  type: NodePort
